services:
  fastapi:
    public: true
    build: .
    replicas: 1
    environment:
      - REDIS_URI=redis://default:896b1aaa85d54c0187d540ef4dde6682@moved-oarfish-33546.upstash.io:33546/ #change this REDIS_URI get it from redistogo.com
      - PYTHON_ENV=prod
      - CACHE_EXPIRATION=180
    ports:
      - 8080
    resources:
      requests:
        cpu: 500m
        memory: 1500Mi
      limits:
        cpu: 1000m
        memory: 3000Mi
